name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Install tflint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Install tfsec
      run: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

    - name: Terraform Format Check
      run: terraform fmt -check -recursive .

    - name: Validate Dev Environment
      working-directory: ./environments/dev
      run: |
        terraform init -backend=false
        terraform validate

    - name: Validate Staging Environment
      working-directory: ./environments/staging
      run: |
        terraform init -backend=false
        terraform validate

    - name: Validate Production Environment
      working-directory: ./environments/production
      run: |
        terraform init -backend=false
        terraform validate

    - name: Validate Modules
      run: |
        for module in modules/*; do
          if [ -d "$module" ]; then
            echo "Validating $module"
            cd "$module"
            terraform init -backend=false
            terraform validate
            cd - > /dev/null
          fi
        done

    - name: Run tflint
      run: |
        find . -name "*.tf" -not -path "./.terraform/*" -exec dirname {} \; | sort -u | while read dir; do
          echo "Running tflint in $dir"
          cd "$dir"
          tflint --init
          tflint
          cd - > /dev/null
        done

    - name: Run tfsec
      run: tfsec . --soft-fail